version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000" # For PHP-FPM, if you need direct access
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mariadb:10.6
    container_name: ${PROJECT_NAME}_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MARIADB_DATABASE: ${DB_DATABASE:-${PROJECT_NAME}}
      MARIADB_USER: ${DB_USERNAME:-user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
